spring:
    jpa:
        hibernate:
            ddl-auto: update
    mail:
        host: smtp.gmail.com
        port: 587
        username: <username>
        password: <password>
        debug: false
        protocol: smtp
        smtp:
            auth: true
            starttls:
                enable:true
    datasource:
        url: jdbc:mysql://localhost:3306/olivia
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver

